runtime: go
api_version: go1

handlers:
- url: /worker/.*
  script: _go_app
  login: admin

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static/
  static_dir: static

- url: /api/.*
  script: _go_app
  secure: optional # Actually not optional, but the api will fail if https is not used rather than redirect.

- url: /.*
  script: _go_app
  secure: always
  redirect_http_response_code: 301